### ISSUE TITLE
Support MacOS

### ISSUE THREAD

**Issue by NicklasTegner** [dennisvang/notsotuf#6]
Hi.
After reading the readme and thinking, I would highly advice to make MacOS support a requirement for version 1.0.
Very few people (including myself) would sadly not be able to use this library, just because it doesn't support MacOS.

**Comment by dennisvang** [comment]
@NicklasTegner Thanks for the suggestion, I agree that it would be better to have Mac OS (and Linux) support.

Personally I do not have access to a Mac, nor do I have any experience developing for Mac OS, so it a bit difficult for me to provide active support there.

I expect the package mostly works on MacOS, out-of-the-box, because the only platform-specific part is the part that does the copying and restarting of the app, in [notsotuf.utils.windows][1]. The [Client.update()][2] method has a `move_and_exit` argument, allowing you to provide a custom, platform-specific, callable that handles the application files after unpacking.

If you would be willing to try this out on a Mac, that would be greatly appreciated.

[1]: https://github.com/dennisvang/notsotuf/blob/master/src/notsotuf/utils/windows.py
[2]: https://github.com/dennisvang/notsotuf/blob/master/src/notsotuf/client.py#L87

**Comment by NicklasTegner** [comment]
@dennisvang  I'll see what I can do, depending on what your over all plans are for this (as I asked in #5 )
But I have some experience doing cross platform updating systems (check my profile for references)

**Comment by dennisvang** [comment]
@NicklasTegner Great!

I think the repo-side should work out-of-the-box on all platforms, as it mostly contains some wrappers around `python-tuf`. I did a quick test on linux as well.

The client-side does have platform specific stuff, but I've tried to contain this in `notsotuf.utils`.

The platform-specific stuff is mainly related to installation paths and to the ability to move/modifiy/delete files while a process is running.

Installation paths need to be specified explicitly by the app developer. Unlike PyUpdater, we do not presume to know where everything should be located on different platforms.

When `client.update()` is called, notsotuf automatically extracts the latest archive into the `client.extract_dir`, and then calls `move_and_exit` to copy or move the extracted files to the final location, which is the `client.app_install_dir`. Both these directories must be specified by the application developer when the `Client` is initialized. Also see the [client-example][2].

In theory you should be able to define a function similar to [start_script_and_exit()][1], aimed at MacOS, and pass that into the update call, as follows: `client.update(move_and_exit=my_mac_function)`, but I haven't tested this yet.

The `move_and_exit` callable receives two paths, as can be seen here:

https://github.com/dennisvang/notsotuf/blob/1321f81b499c36c743287de3c6e1106bdb01344c/src/notsotuf/client.py#L214

The callable should do what the name implies: move the files and exit the application (or you could try to restart the application if you wish). You can do other things there as well, if needed.

NOTE: I think I'll rename the `move_and_exit` argument in `Client.update()` to something more generic, like `installation_callable` or `after_extract_call`.

[1]: https://github.com/dennisvang/notsotuf/blob/master/src/notsotuf/utils/windows.py#L20
[2]: https://github.com/dennisvang/notsotuf/blob/master/examples/client/example_app.py

**Comment by NicklasTegner** [comment]
and just because I'm curious
Why don't we assume where we can extract updates? I mean, it works for PyUpdater, and the installation directory (where the application is located) is gotten from where the executable was run. What usecase are there for not assuming this?

I can't think of any, so if we can't just assume outright, I would at least make an util function to set the paths like what PyUpdater does, for simplicitys sake
